org: leomontoya
service: api-salas

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 256MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::087688905490:role/LabRole
  environment:
    TABLE_NAME_SALAS: ${sls:stage}-tp_salas
    LAMBDA_VALIDAR_TOKEN: api-usuarios-${sls:stage}-validar_token
    LAMBDA_BUSCAR_CINE: api-cines-${sls:stage}-buscar_cine

functions:
  crear_sala:
    handler: LambdaCrearSala.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /sala/crear
          method: post
          cors: true
          integration: lambda
  buscar_sala:
    handler: LmabdaBuscarSala.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /sala/buscar
          method: post
          cors: true
          integration: lambda
  modificar_cine:
    handler: LambdaModificarSala.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /sala/modificar
          method: put
          cors: true
          integration: lambda

resources:
  Resources:
    TablaCines:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_SALAS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: sala_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: sala_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
